set -g status-style 'bg=#333333 fg=#5eacd3'
set -g status-right ""

set-option -ga terminal-overrides ",*-256color*:Tc"

set -g status on
set -g mouse on
set-window-option -g mode-keys vi

set -g history-limit 5000
set -s escape-time 50

# start windows and panes index at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# make sure windows get renumbered after delete
set -g renumber-windows on

# tail of path as window name
set -g status-interval 5
set -g automatic-rename on
set -g automatic-rename-format '#(basename "#{pane_current_path}")'

# set C-a as tmux prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# keymap to reload tmux config
bind r source-file ~/.tmux.conf \; display "Reloaded"

# unbind " and % bc they're not used to split windows but | and - are
unbind '"'
unbind %

# split panes using | and -, make sure they open in the same path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# open new window at current path
bind C new-window -c "#{pane_current_path}"

# open popup window in current directory
bind-key t display-popup -d "#{pane_current_path}" -w 90% -h 90% -E
# open lazygit in popup window in current directory
bind-key T display-popup -d "#{pane_current_path}" -w 95% -h 95% -E lazygit

# keymap to start tmux-sessionizer
# bind-key -r E run-shell "tmux neww ~/bin/tmux-sessionizer
# bind-key -r E run-shell "tmux neww ~/.local/scripts/tmux-sessionizer.sh"
# bind-key -r R run-shell "tmux new-window tmux-sessionizer -s 0"

# List of tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# set-environment -g TMUX_PLUGIN_MANAGER_PATH="~/.tmux/tpm-plugins"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
